name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Change gradle permission
        run: chmod -x gradlew

      - name: Run a one-line script
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: ./gradlew test



