name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Change gradle permission
        run: chmod 777 gradlew

      - name: Assemble
        run: ./gradlew assemble
        
      - name: Run unit tests
        run: ./gradlew test
